import os
import certifi

# --- 1. SSL CERTIFICATE PATCH (CRITICAL ORDER) ---
# MUST be executed BEFORE any network-reliant library (discord, aiohttp, google) 
# is even imported to ensure the environment variables are locked in.
os.environ['SSL_CERT_FILE'] = certifi.where()
os.environ['REQUESTS_CA_BUNDLE'] = certifi.where()

import asyncio
import sqlite3
import logging
import signal
from datetime import datetime

# Now safe to import network-reliant libraries
import discord
from discord.ext import commands
from aiohttp import web
from dotenv import load_dotenv
import google.generativeai as genai

# =============================================================================
# 1. CONFIGURATION & ENVIRONMENT
# =============================================================================

# Load .env file for local development. On Hugging Face, secrets are injected
# directly as environment variables and load_dotenv() gracefully does nothing.
load_dotenv()

# --- Required Secrets ---
DISCORD_TOKEN   = os.getenv('DISCORD_TOKEN')
GEMINI_API_KEY  = os.getenv('GEMINI_API_KEY')
OWNER_ID        = os.getenv('OWNER_ID')          # Your Discord User ID as a string

# --- Optional Configuration ---
# Default points to the current Gemini 3.1 Pro API identifier.
# Override via the GEMINI_MODEL secret in HF Spaces settings.
MODEL_ID = os.getenv('GEMINI_MODEL', 'gemini-2.5-pro-preview-05-06')

# --- Persistent Database Path ---
# On Hugging Face, /data is the mount point for the persistent Storage Bucket.
# Locally, this will just create a /data folder (or you can change it for dev).
DB_PATH = '/data/psyche.db'

# --- Startup Validation ---
if not DISCORD_TOKEN:
    raise EnvironmentError("CRITICAL: DISCORD_TOKEN is not set. Bot cannot start.")
if not GEMINI_API_KEY:
    raise EnvironmentError("CRITICAL: GEMINI_API_KEY is not set. Bot cannot start.")
if not OWNER_ID:
    # Non-fatal, but !query will be inaccessible
    print("WARNING: OWNER_ID is not set. Creator commands will be disabled.")

# =============================================================================
# 2. LOGGING SETUP
# =============================================================================

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(name)s: %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
log = logging.getLogger('psyche')

# Quieten the noisy discord.py and google loggers
logging.getLogger('discord').setLevel(logging.WARNING)
logging.getLogger('google').setLevel(logging.WARNING)

# =============================================================================
# 3. GOOGLE GEMINI CONFIGURATION
# =============================================================================

genai.configure(
    api_key=GEMINI_API_KEY,
    transport='rest'    # REST transport avoids gRPC issues in Docker environments
)
model = genai.GenerativeModel(MODEL_ID)

# Standard disclaimer appended to all AI-generated outputs
DISCLAIMER = (
    "\n\n---\n⚠️ *This analysis is generated by an AI for research and "
    "entertainment purposes only. It is not a clinical or professional assessment.*"
)

# =============================================================================
# 4. DATABASE INITIALIZATION
# =============================================================================

def init_db():
    """
    Creates the SQLite database and all required tables if they don't exist.
    Called once during bot startup via on_ready.
    """
    # Ensure the /data directory exists (important for local dev)
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # -- 1. Message History Table --
    # Stores opted-in user messages for behavioral analysis.
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS messages (
            id        INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id   TEXT NOT NULL,
            guild_id  TEXT NOT NULL,
            content   TEXT NOT NULL,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    # -- 2. Quiz Results Table --
    # Stores completed personality quiz summaries (MBTI type, OCEAN scores).
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS quiz_results (
            user_id      TEXT NOT NULL,
            guild_id     TEXT NOT NULL,
            quiz_type    TEXT NOT NULL,        -- 'mbti' or 'ocean'
            result_summary TEXT,               -- AI-generated summary of the result
            raw_answers  TEXT,                 -- JSON blob of their responses
            completed_at DATETIME,
            PRIMARY KEY (user_id, guild_id, quiz_type)
        )
    ''')

    # -- 3. Active Quiz Sessions Table --
    # Persistent storage for in-progress quizzes (!quiz resume).
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS quiz_sessions (
            user_id          TEXT PRIMARY KEY,
            quiz_type        TEXT NOT NULL,
            current_question INTEGER DEFAULT 0,
            answers          TEXT DEFAULT '[]', -- JSON array of answers so far
            started_at       DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    # -- 4. Cooldowns Table --
    # Tracks the last time a user ran rate-limited commands (!ultimate_analysis).
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS cooldowns (
            user_id   TEXT NOT NULL,
            command   TEXT NOT NULL,
            last_used DATETIME NOT NULL,
            PRIMARY KEY (user_id, command)
        )
    ''')

    conn.commit()
    conn.close()
    log.info("Database initialized at %s", DB_PATH)

# =============================================================================
# 5. PRIVACY & SECURITY UTILITIES
# =============================================================================

def has_opt_in(member: discord.Member) -> bool:
    """
    The Privacy Gatekeeper.
    Returns True only if the user has the 'PsycheOptIn' role (case-insensitive).
    """
    if not isinstance(member, discord.Member):
        return False
    return any(role.name.lower() == "psycheoptin" for role in member.roles)

async def check_cooldown(user_id: str, command: str, cooldown_days: int = 7):
    """
    Checks if a user is still on cooldown for a specific command.
    Returns the datetime they can use it again, or None if they are clear.
    """
    # OWNER_ID bypasses all cooldowns for debugging and pro-use
    if user_id == OWNER_ID:
        return None

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute(
        "SELECT last_used FROM cooldowns WHERE user_id = ? AND command = ?",
        (user_id, command)
    )
    row = cursor.fetchone()
    conn.close()

    if row:
        from datetime import timedelta
        last_used = datetime.fromisoformat(row[0])
        next_use = last_used + timedelta(days=cooldown_days)
        if datetime.now() < next_use:
            return next_use
    
    return None

def set_cooldown(user_id: str, command: str):
    """Updates the cooldown timestamp for a user/command."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute(
        "INSERT OR REPLACE INTO cooldowns (user_id, command, last_used) VALUES (?, ?, ?)",
        (user_id, command, datetime.now().isoformat())
    )
    conn.commit()
    conn.close()

# =============================================================================
# 5. HEARTBEAT WEB SERVER (aiohttp — Lifecycle Managed)
# =============================================================================

class HeartbeatServer:
    """
    Manages the aiohttp lifecycle natively within the bot's event loop.
    Ensures clean startup and graceful shutdown without task leaks.
    """
    def __init__(self, port=7860):
        self.port = port
        self.runner = None

    async def start(self):
        app = web.Application()
        app.router.add_get('/', self.handle_ping)
        
        self.runner = web.AppRunner(app)
        await self.runner.setup()
        
        site = web.TCPSite(self.runner, '0.0.0.0', self.port)
        await site.start()
        log.info("Heartbeat server online at port %s", self.port)

    async def stop(self):
        if self.runner:
            await self.runner.cleanup()
            log.info("Heartbeat server shut down gracefully.")

    async def handle_ping(self, request):
        return web.Response(text="Psyche is Awake", content_type="text/plain")

# =============================================================================
# 6. BOT SETUP
# =============================================================================

# Required intents:
#   - message_content: to read and log user messages
#   - members:         to inspect user roles for the PsycheOptIn gate
intents = discord.Intents.default()
intents.message_content = True
intents.members = True

class PsycheBot(commands.Bot):
    """
    Custom Bot subclass. Manages database initialization, web heartbeat,
    and graceful shutdown sequences.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.web_server = HeartbeatServer(port=7860)

    async def setup_hook(self):
        """Pre-Gateway initialization."""
        # Start web server first to satisfy HF Spaces port check
        await self.web_server.start()
        log.info("setup_hook: Heartbeat server initialized.")

    async def close(self):
        """Cleanup sequence on bot shutdown."""
        log.info("Shutdown signal received. Cleaning up...")
        await self.web_server.stop()
        await super().close()

    async def on_ready(self):
        """Fired once the bot is fully connected and ready to receive events."""
        # Initialize the database (idempotent — safe to call on reconnect)
        init_db()

        # Set a Rich Presence status
        activity = discord.Activity(
            type=discord.ActivityType.watching,
            name="behavioral patterns | !help"
        )
        await self.change_presence(status=discord.Status.online, activity=activity)

        log.info("=" * 50)
        log.info("✨ Psyche v2 Online")
        log.info("   Logged in as : %s (ID: %s)", self.user, self.user.id)
        log.info("   Model        : %s", MODEL_ID)
        log.info("   Servers      : %d", len(self.guilds))
        log.info("   Owner ID     : %s", OWNER_ID or "NOT SET")
        log.info("=" * 50)


bot = PsycheBot(
    command_prefix='!',
    intents=intents,
    help_command=None   # We implement our own !help embed in Phase 5
)

# =============================================================================
# 7. COMMANDS
# =============================================================================

@bot.command(name='ping')
async def ping(ctx: commands.Context):
    """System status check."""
    latency_ms = round(bot.latency * 1000)
    
    # Get some DB stats
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("SELECT COUNT(*) FROM messages")
    msg_count = cursor.fetchone()[0]
    cursor.execute("SELECT COUNT(DISTINCT user_id) FROM messages")
    user_count = cursor.fetchone()[0]
    conn.close()

    embed = discord.Embed(title="🏓 Pong!", color=discord.Color.from_str("#9B59B6"))
    embed.add_field(name="Latency", value=f"`{latency_ms}ms`", inline=True)
    embed.add_field(name="Engine", value=f"`{MODEL_ID}`", inline=True)
    embed.add_field(name="Archived Messages", value=f"`{msg_count:,}`", inline=True)
    embed.add_field(name="Opted-in Users", value=f"`{user_count}`", inline=True)
    embed.set_footer(text="Psyche v2 · Privacy-First Architecture")
    await ctx.send(embed=embed)

@bot.command(name='analyze_me')
async def analyze_me(ctx: commands.Context):
    """
    Behavioral Profiling.
    Scans the user's last 500 messages for linguistic markers and cognitive style.
    """
    # 1. Privacy Check
    if not has_opt_in(ctx.author):
        return await ctx.reply("❌ **Access Denied**: You must have the `PsycheOptIn` role to use this.")

    # 2. Cooldown Check (10 minutes)
    # Note: OWNER_ID and Admins bypass this.
    is_admin = ctx.author.guild_permissions.administrator or str(ctx.author.id) == OWNER_ID
    if not is_admin:
        cd = await check_cooldown(str(ctx.author.id), "analyze_me", cooldown_days=0) # 0 days = check hours/mins
        # For simplicity in this build, we'll use a 10 min hardcode if check_cooldown returns a value
        # But for Phase 3, let's just implement a quick 10-min logic:
        conn = sqlite3.connect(DB_PATH); cursor = conn.cursor()
        cursor.execute("SELECT last_used FROM cooldowns WHERE user_id = ? AND command = 'analyze_me'", (str(ctx.author.id),))
        row = cursor.fetchone(); conn.close()
        if row:
            last = datetime.fromisoformat(row[0])
            from datetime import timedelta
            if datetime.now() < last + timedelta(minutes=10):
                rem = (last + timedelta(minutes=10)) - datetime.now()
                return await ctx.reply(f"⏳ **Cooldown**: Please wait {round(rem.total_seconds()/60)} more minutes.")

    # 3. Data Readiness Check
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute(
        "SELECT content FROM messages WHERE user_id = ? AND guild_id = ? ORDER BY timestamp DESC LIMIT 500",
        (str(ctx.author.id), str(ctx.guild.id))
    )
    rows = cursor.fetchall()
    conn.close()

    if len(rows) < 50:
        return await ctx.reply(f"❌ **Insufficient Data**: I need at least 50 messages to build a baseline (you have {len(rows)}). Chat some more!")

    status_msg = await ctx.send("🧐 **Scanning linguistic markers and emotional patterns...**")

    # 4. AI Synthesis
    chat_log = "\n".join([r[0] for r in rows])
    prompt = (
        f"Perform a deep behavioral analysis on the following chat history. "
        f"Identify linguistic markers, emotional baseline, cognitive style, and "
        f"social dynamics. Be insightful, slightly provocative, but professional. "
        f"User History:\n{chat_log}"
    )

    try:
        response = await asyncio.to_thread(model.generate_content, prompt)
        
        # 5. DM Delivery
        report = f"📊 **Behavioral Profile: {ctx.author.display_name}**\n\n{response.text}{DISCLAIMER}"
        
        try:
            # Handle long responses (split by 2000 chars)
            for chunk in [report[i:i+1900] for i in range(0, len(report), 1900)]:
                await ctx.author.send(chunk)
            
            await status_msg.edit(content="✅ **Analysis complete.** Check your DMs for the full behavioral dossier.")
            set_cooldown(str(ctx.author.id), "analyze_me")
        except discord.Forbidden:
            await status_msg.edit(content="❌ **Delivery Failed**: I can't DM you! Please enable 'Allow direct messages from server members' in your privacy settings.")
    
    except Exception as e:
        log.error("Gemini Error in analyze_me: %s", e)
        await status_msg.edit(content="⚠️ **System Error**: The AI is currently overwhelmed. Please try again in a few minutes.")

@bot.command(name='ultimate_analysis')
async def ultimate_analysis(ctx: commands.Context):
    """
    The Milestone Report.
    Synthesizes chat history + personality quiz results.
    """
    if not has_opt_in(ctx.author):
        return await ctx.reply("❌ **Access Denied**: You must have the `PsycheOptIn` role.")

    # 1. Cooldown Check (7 Days)
    cd = await check_cooldown(str(ctx.author.id), "ultimate_analysis", cooldown_days=7)
    if cd:
        return await ctx.reply(f"⏳ **Cooldown**: This is a major report. You can run it again on `{cd.strftime('%Y-%m-%d')}`.")

    # 2. Data Check (Messages + Quiz)
    conn = sqlite3.connect(DB_PATH); cursor = conn.cursor()
    cursor.execute("SELECT content FROM messages WHERE user_id = ? LIMIT 500", (str(ctx.author.id),))
    msgs = cursor.fetchall()
    cursor.execute("SELECT quiz_type, result_summary FROM quiz_results WHERE user_id = ?", (str(ctx.author.id),))
    quizzes = cursor.fetchall()
    conn.close()

    if len(msgs) < 50 or not quizzes:
        return await ctx.reply("❌ **Missing Requirements**: You need 50+ messages AND at least one completed personality quiz (!take_test).")

    status_msg = await ctx.send("🧪 **Synthesizing multi-modal data points into an Ultimate Dossier...**")

    # 3. AI Synthesis
    chat_log = "\n".join([m[0] for m in msgs])
    quiz_context = "\n".join([f"[{q[0].upper()}] {q[1]}" for q in quizzes])
    
    prompt = (
        f"You are Psyche, a master behavioral psychologist. Synthesize this user's data into a "
        f"definitive psychological dossier (1000+ words). Combine their chat history linguistic "
        f"markers with their personality quiz results. Provide deep insights into their "
        f"subconscious drivers, social mask, and growth potential.\n\n"
        f"Chat Baseline:\n{chat_log}\n\nQuiz Context:\n{quiz_context}"
    )

    try:
        response = await asyncio.to_thread(model.generate_content, prompt)
        
        # 4. DM Delivery
        header = f"🏆 **ULTIMATE PSYCHOLOGICAL DOSSIER: {ctx.author.display_name}**\n"
        full_text = f"{header}\n{response.text}{DISCLAIMER}"
        
        try:
            for chunk in [full_text[i:i+1900] for i in range(0, len(full_text), 1900)]:
                await ctx.author.send(chunk)
            
            await status_msg.edit(content="✅ **Synthesis Complete.** Your Master Dossier has been delivered to your DMs.")
            set_cooldown(str(ctx.author.id), "ultimate_analysis")
        except discord.Forbidden:
            await status_msg.edit(content="❌ **Delivery Failed**: I can't DM you! Please check your privacy settings.")
            
    except Exception as e:
        log.error("Gemini Error in ultimate: %s", e)
        await status_msg.edit(content="⚠️ **Synthesis Failed**: The engine hit a reasoning block. Please try again later.")

# =============================================================================
# 8. EVENTS & PRIVACY HANDLERS
# =============================================================================

@bot.event
async def on_message(message: discord.Message):
    """
    Global message handler.
    1. Ignores all bot messages.
    2. Privacy Gatekeeper: Only logs history for users with 'PsycheOptIn'.
    3. Processes commands.
    """
    if message.author.bot:
        return

    # -- Real-time Behavioral Logging --
    # We only store messages from users who have explicitly opted in via role.
    # We skip DMs and system messages.
    if not isinstance(message.channel, discord.DMChannel) and has_opt_in(message.author):
        try:
            conn = sqlite3.connect(DB_PATH)
            cursor = conn.cursor()
            cursor.execute(
                "INSERT INTO messages (user_id, guild_id, content) VALUES (?, ?, ?)",
                (str(message.author.id), str(message.guild.id), message.content)
            )
            conn.commit()
            conn.close()
        except Exception as e:
            log.error("Failed to log message for %s: %s", message.author, e)

    # IMPORTANT: Process commands
    await bot.process_commands(message)

@bot.event
async def on_guild_remove(guild: discord.Guild):
    """
    The Scrub Protocol.
    Triggered when the bot is kicked from a server or the server is deleted.
    Immediately wipes ALL data associated with that Guild ID from the database.
    """
    log.info("🧹 Scrub Protocol triggered for Guild: %s (ID: %s)", guild.name, guild.id)
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        
        # Wipe messages
        cursor.execute("DELETE FROM messages WHERE guild_id = ?", (str(guild.id),))
        # Wipe quiz results
        cursor.execute("DELETE FROM quiz_results WHERE guild_id = ?", (str(guild.id),))
        
        conn.commit()
        conn.close()
        log.info("✅ Scrub Protocol complete. Data for %s purged.", guild.id)
    except Exception as e:
        log.error("Scrub Protocol FAILED for Guild %s: %s", guild.id, e)

# =============================================================================
# 9. ENTRY POINT
# =============================================================================

if __name__ == '__main__':
    log.info("Starting Psyche v2...")
    log.info("SSL certificates: %s", certifi.where())
    # bot.run() creates and manages the event loop internally.
    # Our setup_hook() and on_ready() handle all async initialization.
    bot.run(DISCORD_TOKEN, reconnect=True, log_handler=None)
