# =============================================================================
# Psyche v2 — Core Bot
# A privacy-first, high-reasoning Discord behavioral analysis bot.
# Powered by Google Gemini 3.1 Pro.
# =============================================================================
#
# ARCHITECTURE NOTE:
# The certifi SSL patch MUST be the very first thing that runs — before any
# network-capable library (discord, google, aiohttp) is imported. This is the
# fix for Hugging Face's strict network security causing "Offline" gateway errors.
#
import os
import certifi

# --- SSL Certificate Patch (MUST BE BEFORE ALL OTHER IMPORTS) ---
# Forces all network traffic to use the certifi bundle instead of the
# system's potentially outdated/missing certificate store.
os.environ['SSL_CERT_FILE'] = certifi.where()
os.environ['REQUESTS_CA_BUNDLE'] = certifi.where()

# =============================================================================
# Standard Library
# =============================================================================
import asyncio
import sqlite3
import logging
from datetime import datetime

# =============================================================================
# Third-Party Imports (safe to load after SSL patch)
# =============================================================================
import discord
from discord.ext import commands
from aiohttp import web                     # aiohttp ships with discord.py — no extra install
from dotenv import load_dotenv
import google.generativeai as genai

# =============================================================================
# 1. CONFIGURATION & ENVIRONMENT
# =============================================================================

# Load .env file for local development. On Hugging Face, secrets are injected
# directly as environment variables and load_dotenv() gracefully does nothing.
load_dotenv()

# --- Required Secrets ---
DISCORD_TOKEN   = os.getenv('DISCORD_TOKEN')
GEMINI_API_KEY  = os.getenv('GEMINI_API_KEY')
OWNER_ID        = os.getenv('OWNER_ID')          # Your Discord User ID as a string

# --- Optional Configuration ---
# Default points to the current Gemini 3.1 Pro API identifier.
# Override via the GEMINI_MODEL secret in HF Spaces settings.
MODEL_ID = os.getenv('GEMINI_MODEL', 'gemini-2.5-pro-preview-05-06')

# --- Persistent Database Path ---
# On Hugging Face, /data is the mount point for the persistent Storage Bucket.
# Locally, this will just create a /data folder (or you can change it for dev).
DB_PATH = '/data/psyche.db'

# --- Startup Validation ---
if not DISCORD_TOKEN:
    raise EnvironmentError("CRITICAL: DISCORD_TOKEN is not set. Bot cannot start.")
if not GEMINI_API_KEY:
    raise EnvironmentError("CRITICAL: GEMINI_API_KEY is not set. Bot cannot start.")
if not OWNER_ID:
    # Non-fatal, but !query will be inaccessible
    print("WARNING: OWNER_ID is not set. Creator commands will be disabled.")

# =============================================================================
# 2. LOGGING SETUP
# =============================================================================

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(name)s: %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
log = logging.getLogger('psyche')

# Quieten the noisy discord.py and google loggers
logging.getLogger('discord').setLevel(logging.WARNING)
logging.getLogger('google').setLevel(logging.WARNING)

# =============================================================================
# 3. GOOGLE GEMINI CONFIGURATION
# =============================================================================

genai.configure(
    api_key=GEMINI_API_KEY,
    transport='rest'    # REST transport avoids gRPC issues in Docker environments
)
model = genai.GenerativeModel(MODEL_ID)

# Standard disclaimer appended to all AI-generated outputs
DISCLAIMER = (
    "\n\n---\n⚠️ *This analysis is generated by an AI for research and "
    "entertainment purposes only. It is not a clinical or professional assessment.*"
)

# =============================================================================
# 4. DATABASE INITIALIZATION
# =============================================================================

def init_db():
    """
    Creates the SQLite database and all required tables if they don't exist.
    Called once during bot startup via on_ready.
    """
    # Ensure the /data directory exists (important for local dev)
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # -- 1. Message History Table --
    # Stores opted-in user messages for behavioral analysis.
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS messages (
            id        INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id   TEXT NOT NULL,
            guild_id  TEXT NOT NULL,
            content   TEXT NOT NULL,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    # -- 2. Quiz Results Table --
    # Stores completed personality quiz summaries (MBTI type, OCEAN scores).
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS quiz_results (
            user_id      TEXT NOT NULL,
            guild_id     TEXT NOT NULL,
            quiz_type    TEXT NOT NULL,        -- 'mbti' or 'ocean'
            result_summary TEXT,               -- AI-generated summary of the result
            raw_answers  TEXT,                 -- JSON blob of their responses
            completed_at DATETIME,
            PRIMARY KEY (user_id, guild_id, quiz_type)
        )
    ''')

    # -- 3. Active Quiz Sessions Table --
    # Persistent storage for in-progress quizzes (!quiz resume).
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS quiz_sessions (
            user_id          TEXT PRIMARY KEY,
            quiz_type        TEXT NOT NULL,
            current_question INTEGER DEFAULT 0,
            answers          TEXT DEFAULT '[]', -- JSON array of answers so far
            started_at       DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    # -- 4. Cooldowns Table --
    # Tracks the last time a user ran rate-limited commands (!ultimate_analysis).
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS cooldowns (
            user_id   TEXT NOT NULL,
            command   TEXT NOT NULL,
            last_used DATETIME NOT NULL,
            PRIMARY KEY (user_id, command)
        )
    ''')

    conn.commit()
    conn.close()
    log.info("Database initialized at %s", DB_PATH)

# =============================================================================
# 5. PRIVACY & SECURITY UTILITIES
# =============================================================================

def has_opt_in(member: discord.Member) -> bool:
    """
    The Privacy Gatekeeper.
    Returns True only if the user has the 'PsycheOptIn' role (case-insensitive).
    """
    if not isinstance(member, discord.Member):
        return False
    return any(role.name.lower() == "psycheoptin" for role in member.roles)

async def check_cooldown(user_id: str, command: str, cooldown_days: int = 7):
    """
    Checks if a user is still on cooldown for a specific command.
    Returns the datetime they can use it again, or None if they are clear.
    """
    # OWNER_ID bypasses all cooldowns for debugging and pro-use
    if user_id == OWNER_ID:
        return None

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute(
        "SELECT last_used FROM cooldowns WHERE user_id = ? AND command = ?",
        (user_id, command)
    )
    row = cursor.fetchone()
    conn.close()

    if row:
        from datetime import timedelta
        last_used = datetime.fromisoformat(row[0])
        next_use = last_used + timedelta(days=cooldown_days)
        if datetime.now() < next_use:
            return next_use
    
    return None

def set_cooldown(user_id: str, command: str):
    """Updates the cooldown timestamp for a user/command."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute(
        "INSERT OR REPLACE INTO cooldowns (user_id, command, last_used) VALUES (?, ?, ?)",
        (user_id, command, datetime.now().isoformat())
    )
    conn.commit()
    conn.close()

# =============================================================================
# 5. HEARTBEAT WEB SERVER (aiohttp — native async, no threading)
# =============================================================================

async def heartbeat_handler(request):
    """
    Responds to HTTP GET / with a plain-text status message.
    Hugging Face checks this endpoint to confirm the Space is 'Running'.
    """
    return web.Response(text="Psyche is Awake")

async def start_heartbeat():
    """
    Starts the aiohttp web server on 0.0.0.0:7860.
    Runs natively in the event loop — no threads, no blocking.
    Called from PsycheBot.setup_hook() so it starts before the bot connects.
    """
    web_app = web.Application()
    web_app.router.add_get('/', heartbeat_handler)

    runner = web.AppRunner(web_app)
    await runner.setup()

    site = web.TCPSite(runner, host='0.0.0.0', port=7860)
    await site.start()

    log.info("Heartbeat server listening on http://0.0.0.0:7860")

# =============================================================================
# 6. BOT SETUP
# =============================================================================

# Required intents:
#   - message_content: to read and log user messages
#   - members:         to inspect user roles for the PsycheOptIn gate
intents = discord.Intents.default()
intents.message_content = True
intents.members = True

class PsycheBot(commands.Bot):
    """
    Custom Bot subclass. Using setup_hook() to initialize async resources
    (heartbeat server, DB) before the bot's connection is established.
    """

    async def setup_hook(self):
        """Called by discord.py after login but before connecting to the Gateway."""
        # Start the heartbeat server so HF Spaces sees port 7860 immediately
        await start_heartbeat()
        log.info("setup_hook complete.")

    async def on_ready(self):
        """Fired once the bot is fully connected and ready to receive events."""
        # Initialize the database (idempotent — safe to call on reconnect)
        init_db()

        # Set a Rich Presence status
        activity = discord.Activity(
            type=discord.ActivityType.watching,
            name="behavioral patterns | !help"
        )
        await self.change_presence(status=discord.Status.online, activity=activity)

        log.info("=" * 50)
        log.info("✨ Psyche v2 Online")
        log.info("   Logged in as : %s (ID: %s)", self.user, self.user.id)
        log.info("   Model        : %s", MODEL_ID)
        log.info("   Servers      : %d", len(self.guilds))
        log.info("   Owner ID     : %s", OWNER_ID or "NOT SET")
        log.info("=" * 50)


bot = PsycheBot(
    command_prefix='!',
    intents=intents,
    help_command=None   # We implement our own !help embed in Phase 5
)

# =============================================================================
# 7. COMMANDS
# =============================================================================

@bot.command(name='ping')
async def ping(ctx: commands.Context):
    """
    System status check. Returns latency in milliseconds.
    Available to all users — no role gate required.
    """
    latency_ms = round(bot.latency * 1000)

    embed = discord.Embed(
        title="🏓 Pong!",
        color=discord.Color.from_str("#9B59B6")  # Psyche purple
    )
    embed.add_field(name="Latency", value=f"`{latency_ms}ms`", inline=True)
    embed.add_field(name="Engine", value=f"`{MODEL_ID}`", inline=True)
    embed.add_field(name="Status", value="`Online`", inline=True)
    embed.set_footer(text="Psyche v2 · Privacy-First Architecture")

    await ctx.send(embed=embed)

# =============================================================================
# 8. EVENTS & PRIVACY HANDLERS
# =============================================================================

@bot.event
async def on_message(message: discord.Message):
    """
    Global message handler.
    1. Ignores all bot messages.
    2. Privacy Gatekeeper: Only logs history for users with 'PsycheOptIn'.
    3. Processes commands.
    """
    if message.author.bot:
        return

    # -- Real-time Behavioral Logging --
    # We only store messages from users who have explicitly opted in via role.
    # We skip DMs and system messages.
    if not isinstance(message.channel, discord.DMChannel) and has_opt_in(message.author):
        try:
            conn = sqlite3.connect(DB_PATH)
            cursor = conn.cursor()
            cursor.execute(
                "INSERT INTO messages (user_id, guild_id, content) VALUES (?, ?, ?)",
                (str(message.author.id), str(message.guild.id), message.content)
            )
            conn.commit()
            conn.close()
        except Exception as e:
            log.error("Failed to log message for %s: %s", message.author, e)

    # IMPORTANT: Process commands
    await bot.process_commands(message)

@bot.event
async def on_guild_remove(guild: discord.Guild):
    """
    The Scrub Protocol.
    Triggered when the bot is kicked from a server or the server is deleted.
    Immediately wipes ALL data associated with that Guild ID from the database.
    """
    log.info("🧹 Scrub Protocol triggered for Guild: %s (ID: %s)", guild.name, guild.id)
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        
        # Wipe messages
        cursor.execute("DELETE FROM messages WHERE guild_id = ?", (str(guild.id),))
        # Wipe quiz results
        cursor.execute("DELETE FROM quiz_results WHERE guild_id = ?", (str(guild.id),))
        
        conn.commit()
        conn.close()
        log.info("✅ Scrub Protocol complete. Data for %s purged.", guild.id)
    except Exception as e:
        log.error("Scrub Protocol FAILED for Guild %s: %s", guild.id, e)

# =============================================================================
# 9. ENTRY POINT
# =============================================================================

if __name__ == '__main__':
    log.info("Starting Psyche v2...")
    log.info("SSL certificates: %s", certifi.where())
    # bot.run() creates and manages the event loop internally.
    # Our setup_hook() and on_ready() handle all async initialization.
    bot.run(DISCORD_TOKEN, reconnect=True, log_handler=None)
