# =============================================================================
# Psyche v2 — Core Bot
# A privacy-first, high-reasoning Discord behavioral analysis bot.
# Powered by Google Gemini 3.1 Pro.
# =============================================================================
#
# ARCHITECTURE NOTE:
# The certifi SSL patch MUST be the very first thing that runs — before any
# network-capable library (discord, google, aiohttp) is imported. This is the
# fix for Hugging Face's strict network security causing "Offline" gateway errors.
#
import os
import certifi

# --- SSL Certificate Patch (MUST BE BEFORE ALL OTHER IMPORTS) ---
# Forces all network traffic to use the certifi bundle instead of the
# system's potentially outdated/missing certificate store.
os.environ['SSL_CERT_FILE'] = certifi.where()
os.environ['REQUESTS_CA_BUNDLE'] = certifi.where()

# =============================================================================
# Standard Library
# =============================================================================
import asyncio
import sqlite3
import logging
from datetime import datetime

# =============================================================================
# Third-Party Imports (safe to load after SSL patch)
# =============================================================================
import discord
from discord.ext import commands
from aiohttp import web                     # aiohttp ships with discord.py — no extra install
from dotenv import load_dotenv
import google.generativeai as genai

# =============================================================================
# 1. CONFIGURATION & ENVIRONMENT
# =============================================================================

# Load .env file for local development. On Hugging Face, secrets are injected
# directly as environment variables and load_dotenv() gracefully does nothing.
load_dotenv()

# --- Required Secrets ---
DISCORD_TOKEN   = os.getenv('DISCORD_TOKEN')
GEMINI_API_KEY  = os.getenv('GEMINI_API_KEY')
OWNER_ID        = os.getenv('OWNER_ID')          # Your Discord User ID as a string

# --- Optional Configuration ---
# Default points to the current Gemini 3.1 Pro API identifier.
# Override via the GEMINI_MODEL secret in HF Spaces settings.
MODEL_ID = os.getenv('GEMINI_MODEL', 'gemini-2.5-pro-preview-05-06')

# --- Persistent Database Path ---
# On Hugging Face, /data is the mount point for the persistent Storage Bucket.
# Locally, this will just create a /data folder (or you can change it for dev).
DB_PATH = '/data/psyche.db'

# --- Startup Validation ---
if not DISCORD_TOKEN:
    raise EnvironmentError("CRITICAL: DISCORD_TOKEN is not set. Bot cannot start.")
if not GEMINI_API_KEY:
    raise EnvironmentError("CRITICAL: GEMINI_API_KEY is not set. Bot cannot start.")
if not OWNER_ID:
    # Non-fatal, but !query will be inaccessible
    print("WARNING: OWNER_ID is not set. Creator commands will be disabled.")

# =============================================================================
# 2. LOGGING SETUP
# =============================================================================

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(name)s: %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
log = logging.getLogger('psyche')

# Quieten the noisy discord.py and google loggers
logging.getLogger('discord').setLevel(logging.WARNING)
logging.getLogger('google').setLevel(logging.WARNING)

# =============================================================================
# 3. GOOGLE GEMINI CONFIGURATION
# =============================================================================

genai.configure(
    api_key=GEMINI_API_KEY,
    transport='rest'    # REST transport avoids gRPC issues in Docker environments
)
model = genai.GenerativeModel(MODEL_ID)

# Standard disclaimer appended to all AI-generated outputs
DISCLAIMER = (
    "\n\n---\n⚠️ *This analysis is generated by an AI for research and "
    "entertainment purposes only. It is not a clinical or professional assessment.*"
)

# =============================================================================
# 4. DATABASE INITIALIZATION
# =============================================================================

def init_db():
    """
    Creates the SQLite database and all required tables if they don't exist.
    Called once during bot startup via on_ready.
    """
    # Ensure the /data directory exists (important for local dev)
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)

    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    # -- Message History Table --
    # Stores opted-in user messages for behavioral analysis.
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS messages (
            id        INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id   TEXT NOT NULL,
            guild_id  TEXT NOT NULL,
            content   TEXT NOT NULL,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    # -- Quiz Results Table --
    # Stores completed personality quiz results per user per server.
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS quiz_results (
            user_id      TEXT NOT NULL,
            guild_id     TEXT NOT NULL,
            quiz_type    TEXT NOT NULL,
            result_summary TEXT,
            raw_answers  TEXT,
            completed_at DATETIME,
            PRIMARY KEY (user_id, guild_id, quiz_type)
        )
    ''')

    # -- Active Quiz Sessions Table --
    # Allows users to pause and resume in-progress quizzes.
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS quiz_sessions (
            user_id          TEXT PRIMARY KEY,
            quiz_type        TEXT NOT NULL,
            current_question INTEGER DEFAULT 0,
            answers          TEXT DEFAULT '[]',
            started_at       DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    # -- Cooldowns Table --
    # Tracks the last time a user ran a rate-limited command.
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS cooldowns (
            user_id   TEXT NOT NULL,
            command   TEXT NOT NULL,
            last_used DATETIME NOT NULL,
            PRIMARY KEY (user_id, command)
        )
    ''')

    conn.commit()
    conn.close()
    log.info("Database initialized at %s", DB_PATH)

# =============================================================================
# 5. HEARTBEAT WEB SERVER (aiohttp — native async, no threading)
# =============================================================================

async def heartbeat_handler(request):
    """
    Responds to HTTP GET / with a plain-text status message.
    Hugging Face checks this endpoint to confirm the Space is 'Running'.
    """
    return web.Response(text="Psyche is Awake")

async def start_heartbeat():
    """
    Starts the aiohttp web server on 0.0.0.0:7860.
    Runs natively in the event loop — no threads, no blocking.
    Called from PsycheBot.setup_hook() so it starts before the bot connects.
    """
    web_app = web.Application()
    web_app.router.add_get('/', heartbeat_handler)

    runner = web.AppRunner(web_app)
    await runner.setup()

    site = web.TCPSite(runner, host='0.0.0.0', port=7860)
    await site.start()

    log.info("Heartbeat server listening on http://0.0.0.0:7860")

# =============================================================================
# 6. BOT SETUP
# =============================================================================

# Required intents:
#   - message_content: to read and log user messages
#   - members:         to inspect user roles for the PsycheOptIn gate
intents = discord.Intents.default()
intents.message_content = True
intents.members = True

class PsycheBot(commands.Bot):
    """
    Custom Bot subclass. Using setup_hook() to initialize async resources
    (heartbeat server, DB) before the bot's connection is established.
    """

    async def setup_hook(self):
        """Called by discord.py after login but before connecting to the Gateway."""
        # Start the heartbeat server so HF Spaces sees port 7860 immediately
        await start_heartbeat()
        log.info("setup_hook complete.")

    async def on_ready(self):
        """Fired once the bot is fully connected and ready to receive events."""
        # Initialize the database (idempotent — safe to call on reconnect)
        init_db()

        # Set a Rich Presence status
        activity = discord.Activity(
            type=discord.ActivityType.watching,
            name="behavioral patterns | !help"
        )
        await self.change_presence(status=discord.Status.online, activity=activity)

        log.info("=" * 50)
        log.info("✨ Psyche v2 Online")
        log.info("   Logged in as : %s (ID: %s)", self.user, self.user.id)
        log.info("   Model        : %s", MODEL_ID)
        log.info("   Servers      : %d", len(self.guilds))
        log.info("   Owner ID     : %s", OWNER_ID or "NOT SET")
        log.info("=" * 50)


bot = PsycheBot(
    command_prefix='!',
    intents=intents,
    help_command=None   # We implement our own !help embed in Phase 5
)

# =============================================================================
# 7. COMMANDS
# =============================================================================

@bot.command(name='ping')
async def ping(ctx: commands.Context):
    """
    System status check. Returns latency in milliseconds.
    Available to all users — no role gate required.
    """
    latency_ms = round(bot.latency * 1000)

    embed = discord.Embed(
        title="🏓 Pong!",
        color=discord.Color.from_str("#9B59B6")  # Psyche purple
    )
    embed.add_field(name="Latency", value=f"`{latency_ms}ms`", inline=True)
    embed.add_field(name="Engine", value=f"`{MODEL_ID}`", inline=True)
    embed.add_field(name="Status", value="`Online`", inline=True)
    embed.set_footer(text="Psyche v2 · Privacy-First Architecture")

    await ctx.send(embed=embed)

# =============================================================================
# 8. EVENTS
# =============================================================================

@bot.event
async def on_message(message: discord.Message):
    """
    Global message handler.
    - Ignores all bot messages.
    - Processes commands.
    NOTE: Message logging (for opted-in users) will be added in Phase 2.
    """
    if message.author.bot:
        return

    # IMPORTANT: Must call this to allow commands to be processed.
    await bot.process_commands(message)

# =============================================================================
# 9. ENTRY POINT
# =============================================================================

if __name__ == '__main__':
    log.info("Starting Psyche v2...")
    log.info("SSL certificates: %s", certifi.where())
    # bot.run() creates and manages the event loop internally.
    # Our setup_hook() and on_ready() handle all async initialization.
    bot.run(DISCORD_TOKEN, reconnect=True, log_handler=None)
